rate-limit:
#  header: X-Rate-Limit-Key
#  capacity: 10
#  duration: 1m
  api:
    - key: api-1
      paths:
        - /api/v1/random-data/numeric
      config:
        capacity: 5
        duration: 1m
    - key: api-2
      paths:
        - /api/v1/random-data/alphabetic
      config:
        capacity: 2
        duration: 30s